### ISSUE TITLE
So i was wondering how do I download Swem on aternos 1.20.1 forge when there is no mods found?

### ISSUE THREAD

**Issue by UwUsheep** [FloweringTre/Tre-Tack-Shop--1.18.2#8]

**Comment by UwUsheep** [comment]
Sorry if this is off topic

**Comment by FloweringTre** [comment]
Sorry but this conversation is better suited for the SWEM discord and team as I don't know what is happening with the SWEM mod when it comes to the 1.20.1 and how it is connecting to other sites like Aternos. 
https://discord.gg/swequestrianmod-715626418893095012

I will mention that the SWEM 1.20.1 does not appear in the CurseForge downloader and has to be manually downloaded from the CurseForge or Modrinth site due to it using the NeoForge loader as a main loader form and that is a known issue with the 1.20.1 version. That may be part of the reason why Aternos is having an issue with it but again, this is only a theory as I am not on the Aternos team nor the SWEM team. I am sorry I can't better support your question <3
